# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package Deployment

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: cd health-record-system && npm ci
    - run: cd health-record-system && npm run build --if-present
      env:
        CI: false

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          registry-url: https://registry.npmjs.org/
      - run: cd health-record-system && npm ci
      - run: cd health-record-system && npm install --save err && npm config set registry https://registry.npmjs.org/
      - run: cd health-record-system && npm run build --if-present && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          CI: false
